criteo:
  train:
    _target_: src.datasets.control_dataset.ControlDataset
    section: 'criteo'
    limit: 300000
    split: 'train'
    outcome_column_name: 'visit'

  test:
    _target_: src.datasets.control_dataset.ControlDataset
    section: 'criteo'
    limit: null
    split: 'test'
    outcome_column_name: 'visit'
