x5:
  train:
    _target_: src.datasets.control_dataset.ControlDataset
    section: 'x5'
    limit: 300000
    split: 'train'
    outcome_column_name: 'Y'

  test:
    _target_: src.datasets.control_dataset.ControlDataset
    section: 'x5'
    limit: null
    split: 'test'
    outcome_column_name: 'Y'
