train:
  _target_: src.datasets.uplift_dataset.UpliftDataset
  index: ${oc.env:X5_TRAIN_INDEX}
  limit: null
  shuffle_index: true

val:
  _target_: src.datasets.uplift_dataset.UpliftDataset
  index: ${oc.env:X5_VAL_INDEX}
  limit: null
  shuffle_index: false

test:
  _target_: src.datasets.uplift_dataset.UpliftDataset
  index: ${oc.env:X5_TEST_INDEX}
  limit: null
  shuffle_index: false
