defaults:
  - model: [dragonnet, tarnet, cfrnet, efin, descn, s_learner]
  - datasets: [hillstrom]
  - metrics: uplift
  - _self_

global_setings:
  seed: 42

wandb:
  enabled: false
  project: hype-check
  entity: hype-check
  run_name: null

eval:
  num_bootstraps: 200
  quantile: [0.05, 0.95]
